name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Set up JDK 1.8
      # uses: actions/setup-java@v1
      # with:
      #   java-version: 1.8
    # - name: Build with Maven
      # run: mvn clean install
    - name: Download DesigniteJava
      run: wget "https://www.designite-tools.com/static/download/DJE/DesigniteJava.jar"
    - name: Create 'analysis' folder
      run: mkdir analysis
    - name: Analyze project with DesigniteJava
      run: java -jar DesigniteJava.jar -i ./src -o ./analysis -f XML
    - name: upload
      run: curl -X PUT "https://qscored.com/api/upload/file.xml?is_open_access=on&version=2.1&project_name=DesigniteJava" -H "Authorization: Token ${{ secrets.QSCORED_API_KEY }}" -H "username: ts.iitm@gmail.com" -H "Content-Type: multipart/form-data"  -F 'file=@DesigniteAnalysis.xml'
