name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download DesigniteJava
      run: wget "https://www.designite-tools.com/static/download/DJE/DesigniteJava.jar"
    - name: pwd
      run: pwd
    - name: create folder
      run: mkdir analysis
    - name: ls src
      run: ls src
    - name: ls all
      run: ls -lf
    - name: Analyze project with DesigniteJava
      run: java -jar DesigniteJava.jar -i ./ -o ./
    - name: ls analysis
      run: ls
